#include <beowulf/protocol/get_config.hpp>
#include <beowulf/protocol/config.hpp>
#include <beowulf/protocol/asset.hpp>
#include <beowulf/protocol/types.hpp>
#include <beowulf/protocol/version.hpp>

namespace beowulf { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
   result["TESTNET_BLOCK_LIMIT"] = TESTNET_BLOCK_LIMIT;
#else
   result[ "IS_TEST_NET" ] = false;
#endif
//#ifdef BEOWULF_ENABLE_SMT
   result[ "BEOWULF_ENABLE_SMT" ] = true;
//   result["SMT_MAX_VOTABLE_ASSETS"] = SMT_MAX_VOTABLE_ASSETS;
//   result["SMT_VESTING_WITHDRAW_INTERVAL_SECONDS"] = SMT_VESTING_WITHDRAW_INTERVAL_SECONDS;
//   result["SMT_UPVOTE_LOCKOUT"] = SMT_UPVOTE_LOCKOUT;
//   result["SMT_EMISSION_MIN_INTERVAL_SECONDS"] = SMT_EMISSION_MIN_INTERVAL_SECONDS;
//   result["SMT_EMIT_INDEFINITELY"] = SMT_EMIT_INDEFINITELY;
//   result["SMT_MAX_NOMINAL_VOTES_PER_DAY"] = SMT_MAX_NOMINAL_VOTES_PER_DAY;
//   result["SMT_MAX_VOTES_PER_REGENERATION"] = SMT_MAX_VOTES_PER_REGENERATION;
//   result["SMT_DEFAULT_VOTES_PER_REGEN_PERIOD"] = SMT_DEFAULT_VOTES_PER_REGEN_PERIOD;
//   result["SMT_DEFAULT_PERCENT_CURATION_REWARDS"] = SMT_DEFAULT_PERCENT_CURATION_REWARDS;
   result["SMT_TOKEN_CREATION_FEE"] = SMT_TOKEN_CREATION_FEE;
//#else
//   result[ "BEOWULF_ENABLE_SMT" ] = false;
//#endif

   result["SBD_SYMBOL"] = SBD_SYMBOL;
   result["BEOWULF_INITIAL_VOTE_POWER_RATE"] = BEOWULF_INITIAL_VOTE_POWER_RATE;
   result["BEOWULF_REDUCED_VOTE_POWER_RATE"] = BEOWULF_REDUCED_VOTE_POWER_RATE;
   result["BEOWULF_100_PERCENT"] = BEOWULF_100_PERCENT;
   result["BEOWULF_1_PERCENT"] = BEOWULF_1_PERCENT;
//   result["BEOWULF_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = BEOWULF_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["BEOWULF_ACTIVE_CHALLENGE_COOLDOWN"] = BEOWULF_ACTIVE_CHALLENGE_COOLDOWN;
   result["BEOWULF_ACTIVE_CHALLENGE_FEE"] = BEOWULF_ACTIVE_CHALLENGE_FEE;
   result["BEOWULF_ADDRESS_PREFIX"] = BEOWULF_ADDRESS_PREFIX;
   result["BEOWULF_APR_PERCENT_MULTIPLY_PER_BLOCK"] = BEOWULF_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["BEOWULF_APR_PERCENT_MULTIPLY_PER_HOUR"] = BEOWULF_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["BEOWULF_APR_PERCENT_MULTIPLY_PER_ROUND"] = BEOWULF_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["BEOWULF_APR_PERCENT_SHIFT_PER_BLOCK"] = BEOWULF_APR_PERCENT_SHIFT_PER_BLOCK;
   result["BEOWULF_APR_PERCENT_SHIFT_PER_HOUR"] = BEOWULF_APR_PERCENT_SHIFT_PER_HOUR;
   result["BEOWULF_APR_PERCENT_SHIFT_PER_ROUND"] = BEOWULF_APR_PERCENT_SHIFT_PER_ROUND;
   result["BEOWULF_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = BEOWULF_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["BEOWULF_BANDWIDTH_PRECISION"] = BEOWULF_BANDWIDTH_PRECISION;
   result["BEOWULF_BLOCKCHAIN_PRECISION"] = BEOWULF_BLOCKCHAIN_PRECISION;
   result["BEOWULF_BLOCKCHAIN_PRECISION_DIGITS"] = BEOWULF_BLOCKCHAIN_PRECISION_DIGITS;
   result["BEOWULF_BLOCKCHAIN_HARDFORK_VERSION"] = BEOWULF_BLOCKCHAIN_HARDFORK_VERSION;
   result["BEOWULF_BLOCKCHAIN_VERSION"] = BEOWULF_BLOCKCHAIN_VERSION;
   result["BEOWULF_BLOCK_INTERVAL"] = BEOWULF_BLOCK_INTERVAL;
   result["BEOWULF_BLOCKS_PER_DAY"] = BEOWULF_BLOCKS_PER_DAY;
   result["BEOWULF_BLOCKS_PER_HOUR"] = BEOWULF_BLOCKS_PER_HOUR;
   result["BEOWULF_BLOCKS_PER_YEAR"] = BEOWULF_BLOCKS_PER_YEAR;
//   result["BEOWULF_CASHOUT_WINDOW_SECONDS"] = BEOWULF_CASHOUT_WINDOW_SECONDS;
//   result["BEOWULF_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = BEOWULF_CASHOUT_WINDOW_SECONDS_PRE_HF12;
//   result["BEOWULF_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = BEOWULF_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["BEOWULF_CHAIN_ID"] = BEOWULF_CHAIN_ID;
   //result["BEOWULF_COMMENT_REWARD_FUND_NAME"] = BEOWULF_COMMENT_REWARD_FUND_NAME;
   //result["BEOWULF_CONTENT_APR_PERCENT"] = BEOWULF_CONTENT_APR_PERCENT;
//   result["BEOWULF_CONTENT_CONSTANT_HF0"] = BEOWULF_CONTENT_CONSTANT_HF0;
   //result["BEOWULF_CONTENT_REWARD_PERCENT"] = BEOWULF_CONTENT_REWARD_PERCENT;
   result["BEOWULF_CONVERSION_DELAY"] = BEOWULF_CONVERSION_DELAY;
   result["BEOWULF_CONVERSION_DELAY_PRE_HF_16"] = BEOWULF_CONVERSION_DELAY_PRE_HF_16;
   result["BEOWULF_CREATE_ACCOUNT_DELEGATION_RATIO"] = BEOWULF_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["BEOWULF_CREATE_ACCOUNT_DELEGATION_TIME"] = BEOWULF_CREATE_ACCOUNT_DELEGATION_TIME;
   result["BEOWULF_CREATE_ACCOUNT_WITH_BEOWULF_MODIFIER"] = BEOWULF_CREATE_ACCOUNT_WITH_BEOWULF_MODIFIER;
   //result["BEOWULF_CURATE_APR_PERCENT"] = BEOWULF_CURATE_APR_PERCENT;
//   result["BEOWULF_DEFAULT_SBD_INTEREST_RATE"] = BEOWULF_DEFAULT_SBD_INTEREST_RATE;
   result["BEOWULF_EQUIHASH_K"] = BEOWULF_EQUIHASH_K;
   result["BEOWULF_EQUIHASH_N"] = BEOWULF_EQUIHASH_N;
   result["BEOWULF_FEED_HISTORY_WINDOW"] = BEOWULF_FEED_HISTORY_WINDOW;
   result["BEOWULF_FEED_HISTORY_WINDOW_PRE_HF_16"] = BEOWULF_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["BEOWULF_FEED_INTERVAL_BLOCKS"] = BEOWULF_FEED_INTERVAL_BLOCKS;
   result["BEOWULF_GENESIS_TIME"] = BEOWULF_GENESIS_TIME;
   result["BEOWULF_HARDFORK_REQUIRED_WITNESSES"] = BEOWULF_HARDFORK_REQUIRED_WITNESSES;
   result["BEOWULF_INFLATION_NARROWING_PERIOD"] = BEOWULF_INFLATION_NARROWING_PERIOD;
   result["BEOWULF_INFLATION_RATE_START_PERCENT"] = BEOWULF_INFLATION_RATE_START_PERCENT;
   result["BEOWULF_INFLATION_RATE_STOP_PERCENT"] = BEOWULF_INFLATION_RATE_STOP_PERCENT;
   result["BEOWULF_INIT_MINER_NAME"] = BEOWULF_INIT_MINER_NAME;
   result["BEOWULF_INIT_PUBLIC_KEY_STR"] = BEOWULF_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["BEOWULF_INIT_PRIVATE_KEY"] = BEOWULF_INIT_PRIVATE_KEY;
#endif
   result["BEOWULF_INIT_SUPPLY"] = BEOWULF_INIT_SUPPLY;
   result["SBD_INIT_SUPPLY"] = SBD_INIT_SUPPLY;
   result["BEOWULF_INIT_TIME"] = BEOWULF_INIT_TIME;
   result["BEOWULF_IRREVERSIBLE_THRESHOLD"] = BEOWULF_IRREVERSIBLE_THRESHOLD;
   result["BEOWULF_LIQUIDITY_APR_PERCENT"] = BEOWULF_LIQUIDITY_APR_PERCENT;
   result["BEOWULF_LIQUIDITY_REWARD_BLOCKS"] = BEOWULF_LIQUIDITY_REWARD_BLOCKS;
   result["BEOWULF_LIQUIDITY_REWARD_PERIOD_SEC"] = BEOWULF_LIQUIDITY_REWARD_PERIOD_SEC;
   result["BEOWULF_LIQUIDITY_TIMEOUT_SEC"] = BEOWULF_LIQUIDITY_TIMEOUT_SEC;
   result["BEOWULF_MAX_ACCOUNT_CREATION_FEE"] = BEOWULF_MAX_ACCOUNT_CREATION_FEE;
   result["BEOWULF_MAX_ACCOUNT_NAME_LENGTH"] = BEOWULF_MAX_ACCOUNT_NAME_LENGTH;
   result["BEOWULF_MAX_ACCOUNT_WITNESS_VOTES"] = BEOWULF_MAX_ACCOUNT_WITNESS_VOTES;
   result["BEOWULF_MAX_ASSET_WHITELIST_AUTHORITIES"] = BEOWULF_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["BEOWULF_MAX_AUTHORITY_MEMBERSHIP"] = BEOWULF_MAX_AUTHORITY_MEMBERSHIP;
   result["BEOWULF_MAX_BLOCK_SIZE"] = BEOWULF_MAX_BLOCK_SIZE;
   result["BEOWULF_SOFT_MAX_BLOCK_SIZE"] = BEOWULF_SOFT_MAX_BLOCK_SIZE;
//   result["BEOWULF_MAX_CASHOUT_WINDOW_SECONDS"] = BEOWULF_MAX_CASHOUT_WINDOW_SECONDS;
//   result["BEOWULF_MAX_COMMENT_DEPTH"] = BEOWULF_MAX_COMMENT_DEPTH;
//   result["BEOWULF_MAX_COMMENT_DEPTH_PRE_HF17"] = BEOWULF_MAX_COMMENT_DEPTH_PRE_HF17;
   result["BEOWULF_MAX_FEED_AGE_SECONDS"] = BEOWULF_MAX_FEED_AGE_SECONDS;
   result["BEOWULF_MAX_INSTANCE_ID"] = BEOWULF_MAX_INSTANCE_ID;
   result["BEOWULF_MAX_MEMO_SIZE"] = BEOWULF_MAX_MEMO_SIZE;
   result["BEOWULF_MAX_WITNESSES"] = BEOWULF_MAX_WITNESSES;
   result["BEOWULF_MAX_MINER_WITNESSES_HF0"] = BEOWULF_MAX_MINER_WITNESSES_HF0;
   result["BEOWULF_MAX_MINER_WITNESSES_HF17"] = BEOWULF_MAX_MINER_WITNESSES_HF17;
//   result["BEOWULF_MAX_PERMLINK_LENGTH"] = BEOWULF_MAX_PERMLINK_LENGTH;
   result["BEOWULF_MAX_PROXY_RECURSION_DEPTH"] = BEOWULF_MAX_PROXY_RECURSION_DEPTH;
   result["BEOWULF_MAX_RATION_DECAY_RATE"] = BEOWULF_MAX_RATION_DECAY_RATE;
   result["BEOWULF_MAX_RESERVE_RATIO"] = BEOWULF_MAX_RESERVE_RATIO;
   result["BEOWULF_MAX_RUNNER_WITNESSES_HF0"] = BEOWULF_MAX_RUNNER_WITNESSES_HF0;
   result["BEOWULF_MAX_RUNNER_WITNESSES_HF17"] = BEOWULF_MAX_RUNNER_WITNESSES_HF17;
   result["BEOWULF_MAX_SATOSHIS"] = BEOWULF_MAX_SATOSHIS;
   result["BEOWULF_MAX_SHARE_SUPPLY"] = BEOWULF_MAX_SHARE_SUPPLY;
   result["BEOWULF_MAX_SIG_CHECK_DEPTH"] = BEOWULF_MAX_SIG_CHECK_DEPTH;
   result["BEOWULF_MAX_SIG_CHECK_ACCOUNTS"] = BEOWULF_MAX_SIG_CHECK_ACCOUNTS;
   result["BEOWULF_MAX_TIME_UNTIL_EXPIRATION"] = BEOWULF_MAX_TIME_UNTIL_EXPIRATION;
   result["BEOWULF_MAX_TRANSACTION_SIZE"] = BEOWULF_MAX_TRANSACTION_SIZE;
   result["BEOWULF_MAX_UNDO_HISTORY"] = BEOWULF_MAX_UNDO_HISTORY;
   result["BEOWULF_MAX_URL_LENGTH"] = BEOWULF_MAX_URL_LENGTH;
   result["BEOWULF_MAX_VOTE_CHANGES"] = BEOWULF_MAX_VOTE_CHANGES;
   result["BEOWULF_MAX_VOTED_WITNESSES_HF0"] = BEOWULF_MAX_VOTED_WITNESSES_HF0;
   result["BEOWULF_MAX_VOTED_WITNESSES_HF17"] = BEOWULF_MAX_VOTED_WITNESSES_HF17;
   result["BEOWULF_MAX_WITHDRAW_ROUTES"] = BEOWULF_MAX_WITHDRAW_ROUTES;
   result["BEOWULF_MAX_WITNESS_URL_LENGTH"] = BEOWULF_MAX_WITNESS_URL_LENGTH;
   //result["BEOWULF_MAX_TRANSFER_FEE"] = BEOWULF_MAX_TRANSFER_FEE;
   result["BEOWULF_MIN_WITNESS_FUND"] = BEOWULF_MIN_WITNESS_FUND;
   result["BEOWULF_MIN_TRANSFER_FEE"] = BEOWULF_MIN_TRANSFER_FEE;
   result["BEOWULF_MIN_ACCOUNT_CREATION_FEE"] = BEOWULF_MIN_ACCOUNT_CREATION_FEE;
   result["BEOWULF_MIN_ACCOUNT_NAME_LENGTH"] = BEOWULF_MIN_ACCOUNT_NAME_LENGTH;
   result["BEOWULF_MIN_BLOCK_SIZE_LIMIT"] = BEOWULF_MIN_BLOCK_SIZE_LIMIT;
   result["BEOWULF_MIN_BLOCK_SIZE"] = BEOWULF_MIN_BLOCK_SIZE;
   //result["BEOWULF_MIN_CONTENT_REWARD"] = BEOWULF_MIN_CONTENT_REWARD;
   //result["BEOWULF_MIN_CURATE_REWARD"] = BEOWULF_MIN_CURATE_REWARD;
//   result["BEOWULF_MIN_PERMLINK_LENGTH"] = BEOWULF_MIN_PERMLINK_LENGTH;
//   result["BEOWULF_MIN_REPLY_INTERVAL"] = BEOWULF_MIN_REPLY_INTERVAL;
//   result["BEOWULF_MIN_REPLY_INTERVAL_HF20"] = BEOWULF_MIN_REPLY_INTERVAL_HF20;
//   result["BEOWULF_MIN_ROOT_COMMENT_INTERVAL"] = BEOWULF_MIN_ROOT_COMMENT_INTERVAL;
//   result["BEOWULF_MIN_VOTE_INTERVAL_SEC"] = BEOWULF_MIN_VOTE_INTERVAL_SEC;
   result["BEOWULF_MINER_ACCOUNT"] = BEOWULF_MINER_ACCOUNT;
   result["BEOWULF_MINER_PAY_PERCENT"] = BEOWULF_MINER_PAY_PERCENT;
   result["BEOWULF_MIN_FEEDS"] = BEOWULF_MIN_FEEDS;
   result["BEOWULF_MINING_REWARD"] = BEOWULF_MINING_REWARD;
   result["BEOWULF_MINING_TIME"] = BEOWULF_MINING_TIME;
   result["BEOWULF_MIN_LIQUIDITY_REWARD"] = BEOWULF_MIN_LIQUIDITY_REWARD;
   result["BEOWULF_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = BEOWULF_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["BEOWULF_MIN_PAYOUT_SBD"] = BEOWULF_MIN_PAYOUT_SBD;
   result["BEOWULF_MIN_POW_REWARD"] = BEOWULF_MIN_POW_REWARD;
   result["BEOWULF_MIN_PRODUCER_REWARD"] = BEOWULF_MIN_PRODUCER_REWARD;
   result["BEOWULF_MIN_TRANSACTION_EXPIRATION_LIMIT"] = BEOWULF_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["BEOWULF_MIN_TRANSACTION_SIZE_LIMIT"] = BEOWULF_MIN_TRANSACTION_SIZE_LIMIT;
   result["BEOWULF_MIN_UNDO_HISTORY"] = BEOWULF_MIN_UNDO_HISTORY;
   result["BEOWULF_NULL_ACCOUNT"] = BEOWULF_NULL_ACCOUNT;
   result["BEOWULF_NUM_INIT_MINERS"] = BEOWULF_NUM_INIT_MINERS;
   result["BEOWULF_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = BEOWULF_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
//   result["BEOWULF_OWNER_AUTH_RECOVERY_PERIOD"] = BEOWULF_OWNER_AUTH_RECOVERY_PERIOD;
   result["BEOWULF_OWNER_CHALLENGE_COOLDOWN"] = BEOWULF_OWNER_CHALLENGE_COOLDOWN;
   result["BEOWULF_OWNER_CHALLENGE_FEE"] = BEOWULF_OWNER_CHALLENGE_FEE;
   result["BEOWULF_OWNER_UPDATE_LIMIT"] = BEOWULF_OWNER_UPDATE_LIMIT;
//   result["BEOWULF_POST_AVERAGE_WINDOW"] = BEOWULF_POST_AVERAGE_WINDOW;
   //result["BEOWULF_POST_REWARD_FUND_NAME"] = BEOWULF_POST_REWARD_FUND_NAME;
//   result["BEOWULF_POST_WEIGHT_CONSTANT"] = BEOWULF_POST_WEIGHT_CONSTANT;
   result["BEOWULF_POW_APR_PERCENT"] = BEOWULF_POW_APR_PERCENT;
   result["BEOWULF_PRODUCER_APR_PERCENT"] = BEOWULF_PRODUCER_APR_PERCENT;
   result["BEOWULF_PROXY_TO_SELF_ACCOUNT"] = BEOWULF_PROXY_TO_SELF_ACCOUNT;
//   result["BEOWULF_SBD_INTEREST_COMPOUND_INTERVAL_SEC"] = BEOWULF_SBD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["BEOWULF_SECONDS_PER_YEAR"] = BEOWULF_SECONDS_PER_YEAR;
//   result["BEOWULF_RECENT_RSHARES_DECAY_TIME_HF19"] = BEOWULF_RECENT_RSHARES_DECAY_TIME_HF19;
//   result["BEOWULF_RECENT_RSHARES_DECAY_TIME_HF17"] = BEOWULF_RECENT_RSHARES_DECAY_TIME_HF17;
   result["BEOWULF_REVERSE_AUCTION_WINDOW_SECONDS_HF6"] = BEOWULF_REVERSE_AUCTION_WINDOW_SECONDS_HF6;
   result["BEOWULF_REVERSE_AUCTION_WINDOW_SECONDS_HF20"] = BEOWULF_REVERSE_AUCTION_WINDOW_SECONDS_HF20;
   result["BEOWULF_ROOT_POST_PARENT"] = BEOWULF_ROOT_POST_PARENT;
//   result["BEOWULF_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = BEOWULF_SAVINGS_WITHDRAW_REQUEST_LIMIT;
//   result["BEOWULF_SAVINGS_WITHDRAW_TIME"] = BEOWULF_SAVINGS_WITHDRAW_TIME;
   result["BEOWULF_SBD_START_PERCENT_HF14"] = BEOWULF_SBD_START_PERCENT_HF14;
   result["BEOWULF_SBD_START_PERCENT_HF20"] = BEOWULF_SBD_START_PERCENT_HF20;
   result["BEOWULF_SBD_STOP_PERCENT_HF14"] = BEOWULF_SBD_STOP_PERCENT_HF14;
   result["BEOWULF_SBD_STOP_PERCENT_HF20"] = BEOWULF_SBD_STOP_PERCENT_HF20;
//   result["BEOWULF_SECOND_CASHOUT_WINDOW"] = BEOWULF_SECOND_CASHOUT_WINDOW;
//   result["BEOWULF_SOFT_MAX_COMMENT_DEPTH"] = BEOWULF_SOFT_MAX_COMMENT_DEPTH;
   result["BEOWULF_START_MINER_VOTING_BLOCK"] = BEOWULF_START_MINER_VOTING_BLOCK;
   result["BEOWULF_START_VESTING_BLOCK"] = BEOWULF_START_VESTING_BLOCK;
   result["BEOWULF_TEMP_ACCOUNT"] = BEOWULF_TEMP_ACCOUNT;
//   result["BEOWULF_UPVOTE_LOCKOUT_HF7"] = BEOWULF_UPVOTE_LOCKOUT_HF7;
//   result["BEOWULF_UPVOTE_LOCKOUT_HF17"] = BEOWULF_UPVOTE_LOCKOUT_HF17;
//   result["BEOWULF_UPVOTE_LOCKOUT_SECONDS"] = BEOWULF_UPVOTE_LOCKOUT_SECONDS;
   result["BEOWULF_VESTING_FUND_PERCENT"] = BEOWULF_VESTING_FUND_PERCENT;
   result["BEOWULF_VESTING_WITHDRAW_INTERVALS"] = BEOWULF_VESTING_WITHDRAW_INTERVALS;
   result["BEOWULF_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = BEOWULF_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["BEOWULF_VESTING_WITHDRAW_INTERVAL_SECONDS"] = BEOWULF_VESTING_WITHDRAW_INTERVAL_SECONDS;
//   result["BEOWULF_VOTE_DUST_THRESHOLD"] = BEOWULF_VOTE_DUST_THRESHOLD;
   result["BEOWULF_VOTING_MANA_REGENERATION_SECONDS"] = BEOWULF_VOTING_MANA_REGENERATION_SECONDS;
   result["BEOWULF_SYMBOL"] = BEOWULF_SYMBOL;
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["BEOWULF_VIRTUAL_SCHEDULE_LAP_LENGTH"] = BEOWULF_VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["BEOWULF_VIRTUAL_SCHEDULE_LAP_LENGTH2"] = BEOWULF_VIRTUAL_SCHEDULE_LAP_LENGTH2;
//   result["BEOWULF_MAX_LIMIT_ORDER_EXPIRATION"] = BEOWULF_MAX_LIMIT_ORDER_EXPIRATION;
//   result["BEOWULF_DELEGATION_RETURN_PERIOD_HF0"] = BEOWULF_DELEGATION_RETURN_PERIOD_HF0;
//   result["BEOWULF_DELEGATION_RETURN_PERIOD_HF20"] = BEOWULF_DELEGATION_RETURN_PERIOD_HF20;
   result["BEOWULF_RD_MIN_DECAY_BITS"] = BEOWULF_RD_MIN_DECAY_BITS;
   result["BEOWULF_RD_MAX_DECAY_BITS"] = BEOWULF_RD_MAX_DECAY_BITS;
   result["BEOWULF_RD_DECAY_DENOM_SHIFT"] = BEOWULF_RD_DECAY_DENOM_SHIFT;
   result["BEOWULF_RD_MAX_POOL_BITS"] = BEOWULF_RD_MAX_POOL_BITS;
   result["BEOWULF_RD_MAX_BUDGET_1"] = BEOWULF_RD_MAX_BUDGET_1;
   result["BEOWULF_RD_MAX_BUDGET_2"] = BEOWULF_RD_MAX_BUDGET_2;
   result["BEOWULF_RD_MAX_BUDGET_3"] = BEOWULF_RD_MAX_BUDGET_3;
   result["BEOWULF_RD_MAX_BUDGET"] = BEOWULF_RD_MAX_BUDGET;
   result["BEOWULF_RD_MIN_DECAY"] = BEOWULF_RD_MIN_DECAY;
   result["BEOWULF_RD_MIN_BUDGET"] = BEOWULF_RD_MIN_BUDGET;
   result["BEOWULF_RD_MAX_DECAY"] = BEOWULF_RD_MAX_DECAY;
//   result["BEOWULF_ACCOUNT_SUBSIDY_PRECISION"] = BEOWULF_ACCOUNT_SUBSIDY_PRECISION;
//   result["BEOWULF_WITNESS_SUBSIDY_BUDGET_PERCENT"] = BEOWULF_WITNESS_SUBSIDY_BUDGET_PERCENT;
//   result["BEOWULF_WITNESS_SUBSIDY_DECAY_PERCENT"] = BEOWULF_WITNESS_SUBSIDY_DECAY_PERCENT;
//   result["BEOWULF_DEFAULT_ACCOUNT_SUBSIDY_DECAY"] = BEOWULF_DEFAULT_ACCOUNT_SUBSIDY_DECAY;
//   result["BEOWULF_DEFAULT_ACCOUNT_SUBSIDY_BUDGET"] = BEOWULF_DEFAULT_ACCOUNT_SUBSIDY_BUDGET;
//   result["BEOWULF_DECAY_BACKSTOP_PERCENT"] = BEOWULF_DECAY_BACKSTOP_PERCENT;
   result["ENABLE_CONVERSION_TO_SBD"] = ENABLE_CONVERSION_TO_SBD;
   result["ENABLE_CONVERSION_FROM_SBD"] = ENABLE_CONVERSION_FROM_SBD;
   result["BEOWULF_1_BEOWULF"] = BEOWULF_1_BEOWULF;
   result["BEOWULF_1_VESTS"] = BEOWULF_1_VESTS;

   return result;
}

} } // beowulf::protocol
